apiVersion: v1
kind: Config
preferences:
  colors: true
current-context: hashicorp-learn
contexts:
- context:
    cluster: ${cluster_name}
    namespace: default
    user: ${user_name}
  name: hashicorp-learn
clusters:
- cluster:
    server: ${endpoint}
    certificate-authority-data: ${cluster_ca}
  name: ${cluster_name}
users:
- name: ${user_name}
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - ${aws_region}
      - eks
      - get-token
      - --cluster-name
      - ${cluster_name}
      command: aws
