apiVersion: v1
kind: Config
preferences:
  colors: true
current-context: hashicorp-learn
contexts:
- context:
    cluster: ${cluster_name}
    namespace: default
  name: hashicorp-learn
clusters:
- cluster:
    server: https://${endpoint}
    certificate-authority-data: ${cluster_ca}
  name: ${cluster_name}
